### ISSUE TITLE
test folder 

### ISSUE THREAD

**Issue by danklotz** [chrisschuerz/aRastoCAT#1]
Hey, 

sorry for bothering already.

Consider putting your "test" folder into the main directory can call it "tests". It is currently in your R directory!
This is custom (see: [example](https://github.com/tidyverse/ggplot2)) and does not infer with package compilation. 

lovely logo 👍  🐈  🐈  🐈

**Comment by chrisschuerz** [comment]
Agree 👍  was quick and dirty solution. Will be changed soon...
